### ISSUE TITLE
Do not use platform-specific C headers.

### ISSUE THREAD

**Issue by fripSide** [eBPF-Research/libebpf#3]
To facilitate libebpf's portability across different OS, we should only rely on [C freestanding headers](https://wiki.osdev.org/C_Library) and other simple LibC headers, which are supported by all libc implementations, ranging from Newlib for embedded devices to mingW Libc for Windows. 

The use of headers like ["<asm-generic/errno-base.h>"](https://github.com/eBPF-Research/libebpf/blob/master/src/libebpf_vm.c#L2)   seems to be Linux-specific, so we can redefine some error codes and avoid relying on it.

**Comment by fripSide** [comment]
I address this issue in this branch: https://github.com/eBPF-Research/libebpf/tree/increase-python-version

**Comment by Officeyutong** [comment]
- `<asm-generic/errno-base.h>` is an error introduced by clangd in my development progress. It should be replaced by `errno.h`
- There are also some dependencies to other non-freestanding libraries, such as string.h. I'll update them

**Comment by fripSide** [comment]
> * `<asm-generic/errno-base.h>` is an error introduced by clangd in my development progress. It should be replaced by `errno.h`
> * There are also some dependencies to other non-freestanding libraries, such as string.h. I'll update them

Sorry for the mistake. In fact, we can use some Libc files such as `string.h` other than freestanding C headers.
To make it easier to port to any OS, we should avoid using the LibC function that relying on `syscall` that are  difficult to be ported to other OS (e.g., ESP32 FreeRTOS). Functions such as `malloc brk`  and `print write` are easy to port. So we can still use them.
